mongodb:
    image: mongo:3.4
    hostname: mongodb
    container_name: mongodb
    expose:
        - "27017"
    command: --smallfiles

orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
        - mongodb
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb

keyrock:
    image: fiware/idm
    hostname: keyrock
    container_name: keyrock
    links:
        - mysql
    expose:
        - "3000"
    ports:
        - "3000:3000"
    environment:
        - DATABASE_HOST=mysql

idas:
    image: fiware/iotagent-ul
    hostname: idas
    container_name: idas
    links:
        - mongodb:mongo
        - orion
    expose:
        - "7896"
        - "4041"
    ports:
        - "7896:7896"
        - "4041:4041"

mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    expose:
        - "3306"
    environment:
        - MYSQL_ROOT_PASSWORD=idm

Wirecloud:
    image: fiware/wirecloud:latest
    hostname: wirecloud
    container_name: wirecloud
    links:
        - keyrock
    expose:
        - "80"
        - "443"
    ports:
        - "80:80"
        - "443:443"

